name: Build APK
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libffi-dev \
            libssl-dev \
            libltdl-dev \
            zlib1g-dev \
            openjdk-17-jdk \
            unzip \
            zip \
            cmake \
            autoconf \
            libtool \
            pkg-config \
            python3-setuptools
          pip install --upgrade pip
          pip install --upgrade buildozer cython setuptools

            - name: Build with Buildozer
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          # 1. Принудительно устанавливаем инструменты нужной версии (34)
          # Это создаст нужные папки, чтобы Бульдозер не тупил
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34" "platform-tools"
          
          # 2. Принимаем все лицензии
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          
          # 3. Запускаем саму сборку
          buildozer android debug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JennyMonitor-Package
          path: bin/*.apk
          
